export const guitars = [
  {
    id: 1,
    name: "Epiphone Les Paul Studio",
    cost: "15 000",
    image: "/guitars-photo/LesPaul.webp",
    firm: "Les Paul",
    type: "electric",
    video: "https://www.youtube.com/watch?v=3vEgqqiScY4&t=36s",
    har: "Серія:	                 Standard\nМатеріал корпусу: Вільха\nОрієнтація:             Правостороння\nРозмір гітари:         Повнорозмірна\nГриф:                  	 Клен\nКріплення грифу:	 На болтах\nНакладка грифа:	 Клен\nПрофіль грифа:	 Стандартний 'С'\nТип звукознімачів: Роздільні сингли\nСхема звукознімачів:	S\nМензура:	          34' (864 мм)\nКількість ладів:	  20\nГарантія:	          12 місяців від виробника\nЕлектроніка:	          AlNiCo 5",
  },
  {
    id: 2,
    name: "Limited Edition American II Telecaster",
    cost: "16500",
    image: "/guitars-photo/fender/telecaster/1/main.jpg",
    images: [
      "/guitars-photo/fender/telecaster/1/1.jpg",
      "/guitars-photo/fender/telecaster/1/2.jpg",
      "/guitars-photo/fender/telecaster/1/3.jpg",
      "/guitars-photo/fender/telecaster/1/4.jpg",
      "/guitars-photo/fender/telecaster/1/5.jpg",
      "/guitars-photo/fender/telecaster/1/6.jpg",
    ],
    firm: "Fender",
    type: "electric",
    video: "https://www.youtube.com/embed/wwlfBBQY2HQ?si=jEzEQRSlouovz-Bk",
    har: "Серія:	                 Standard\nМатеріал корпусу: Вільха\nОрієнтація:             Правостороння\nРозмір гітари:         Повнорозмірна\nГриф:                  	 Клен\nКріплення грифу:	 На болтах\nНакладка грифа:	 Клен\nПрофіль грифа:	 Стандартний 'С'\nТип звукознімачів: Роздільні сингли\nСхема звукознімачів:	S\nМензура:	          34' (864 мм)\nКількість ладів:	  20\nГарантія:	          12 місяців від виробника\nЕлектроніка:	          AlNiCo 5",
  },
  {
    id: 3,
    name: "DELUXE ERIC KRASNO BRIGHTON",
    cost: "72500",
    image: "/guitars-photo/dangelico/solid/1/main.png",
    images: [
      "/guitars-photo/dangelico/solid/1/1.png",
      "/guitars-photo/dangelico/solid/1/2.png",
      "/guitars-photo/dangelico/solid/1/3.png",
      "/guitars-photo/dangelico/solid/1/4.png",
      "/guitars-photo/dangelico/solid/1/5.png",
      "/guitars-photo/dangelico/solid/1/6.png",
    ],
    firm: "D'Angelico",
    type: "electric",
    video: "https://www.youtube.com/embed/k_nV8i9K0SM?si=KFvlqt2XM7RD9eI2",
    har: "Серія:	                 Standard\nМатеріал корпусу: Вільха\nОрієнтація:             Правостороння\nРозмір гітари:         Повнорозмірна\nГриф:                  	 Клен\nКріплення грифу:	 На болтах\nНакладка грифа:	 Клен\nПрофіль грифа:	 Стандартний 'С'\nТип звукознімачів: Роздільні сингли\nСхема звукознімачів:	S\nМензура:	          34' (864 мм)\nКількість ладів:	  20\nГарантія:	          12 місяців від виробника\nЕлектроніка:	          AlNiCo 5",
  },
  {
    id: 4,
    name: "DELUXE BRANDON NIEDERAUER ATLANTIC",
    cost: "73000",
    image: "/guitars-photo/dangelico/solid/2/main.png",
    images: [
      "/guitars-photo/dangelico/solid/2/1.png",
      "/guitars-photo/dangelico/solid/2/2.png",
      "/guitars-photo/dangelico/solid/2/3.png",
      "/guitars-photo/dangelico/solid/2/4.png",
      "/guitars-photo/dangelico/solid/2/5.png",
      "/guitars-photo/dangelico/solid/2/6.png",
    ],
    firm: "D'Angelico",
    type: "electric",
    video: "https://www.youtube.com/embed/Q4GvUBdmHTw?si=yiBc_TB31qjawjvc",
    har: "Серія:	                 Standard\nМатеріал корпусу: Вільха\nОрієнтація:             Правостороння\nРозмір гітари:         Повнорозмірна\nГриф:                  	 Клен\nКріплення грифу:	 На болтах\nНакладка грифа:	 Клен\nПрофіль грифа:	 Стандартний 'С'\nТип звукознімачів: Роздільні сингли\nСхема звукознімачів:	S\nМензура:	          34' (864 мм)\nКількість ладів:	  20\nГарантія:	          12 місяців від виробника\nЕлектроніка:	          AlNiCo 5",
  },
  {
    id: 5,
    name: "Player Precision Bass®",
    cost: "27000",
    image: "/guitars-photo/fender/bass/1/main.jpg",
    images: [
      "/guitars-photo/fender/bass/1/1.jpg",
      "/guitars-photo/fender/bass/1/2.jpg",
      "/guitars-photo/fender/bass/1/3.jpg",
      "/guitars-photo/fender/bass/1/4.jpg",
      "/guitars-photo/fender/bass/1/5.jpg",
      "/guitars-photo/fender/bass/1/6.jpg",
    ],
    firm: "Fender",
    type: "bass",
    video: "https://www.youtube.com/embed/55wAPrIoA6M?si=CzoJPMdesoq6p_dl",
    har: "Серія:	                 Standard\nМатеріал корпусу: Вільха\nОрієнтація:             Правостороння\nРозмір гітари:         Повнорозмірна\nГриф:                  	 Клен\nКріплення грифу:	 На болтах\nНакладка грифа:	 Клен\nПрофіль грифа:	 Стандартний 'С'\nТип звукознімачів: Роздільні сингли\nСхема звукознімачів:	S\nМензура:	          34' (864 мм)\nКількість ладів:	  20\nГарантія:	          12 місяців від виробника\nЕлектроніка:	          AlNiCo 5",
  },
  {
    id: 6,
    name: "FA-125CE Dreadnought",
    cost: "7999",
    image: "/guitars-photo/fender/acoustic/1/main.jpg",
    images: [
      "/guitars-photo/fender/acoustic/1/1.jpg",
      "/guitars-photo/fender/acoustic/1/2.jpg",
      "/guitars-photo/fender/acoustic/1/3.jpg",
      "/guitars-photo/fender/acoustic/1/4.jpg",
      "/guitars-photo/fender/acoustic/1/5.jpg",
      "/guitars-photo/fender/acoustic/1/6.jpg",
    ],
    firm: "Fender",
    type: "acoustic",
    video: "https://www.youtube.com/embed/yJ4-3hO7Rbc?si=ONZvbBm_DlgWry4h",
    har: "Серія:	                 Standard\nМатеріал корпусу: Вільха\nОрієнтація:             Правостороння\nРозмір гітари:         Повнорозмірна\nГриф:                  	 Клен\nКріплення грифу:	 На болтах\nНакладка грифа:	 Клен\nПрофіль грифа:	 Стандартний 'С'\nТип звукознімачів: Роздільні сингли\nСхема звукознімачів:	S\nМензура:	          34' (864 мм)\nКількість ладів:	  20\nГарантія:	          12 місяців від виробника\nЕлектроніка:	          AlNiCo 5",
  },
];
