export const guitars = [
  {
    id: 1,
    name: "Limited Edition American II Telecaster",
    cost: "16500",
    image: "/guitars-photo/fender/telecaster/1/main.jpg",
    images: [
      "/guitars-photo/fender/telecaster/1/1.jpg",
      "/guitars-photo/fender/telecaster/1/2.jpg",
      "/guitars-photo/fender/telecaster/1/3.jpg",
      "/guitars-photo/fender/telecaster/1/4.jpg",
      "/guitars-photo/fender/telecaster/1/5.jpg",
      "/guitars-photo/fender/telecaster/1/6.jpg",
    ],
    firm: "Fender",
    type: "electric",
    video: "https://www.youtube.com/embed/wwlfBBQY2HQ?si=jEzEQRSlouovz-Bk",
    har: "Серія:	                 Standard\nМатеріал корпусу: Вільха\nОрієнтація:             Правостороння\nРозмір гітари:         Повнорозмірна\nГриф:                  	 Клен\nКріплення грифу:	 На болтах\nНакладка грифа:	 Клен\nПрофіль грифа:	 Стандартний 'С'\nТип звукознімачів: Роздільні сингли\nСхема звукознімачів:	S\nМензура:	          34' (864 мм)\nКількість ладів:	  20\nГарантія:	          12 місяців від виробника\nЕлектроніка:	          AlNiCo 5",
    pickup: "S-S",
    frets: "22",
    avail: "Є в наявнсті",
    code: "623545",
    audio: "/audio/electro1.mp3",
  },
  {
    id: 2,
    name: "DELUXE ERIC KRASNO BRIGHTON",
    cost: "72500",
    image: "/guitars-photo/dangelico/solid/1/main.png",
    images: [
      "/guitars-photo/dangelico/solid/1/1.png",
      "/guitars-photo/dangelico/solid/1/2.png",
      "/guitars-photo/dangelico/solid/1/3.png",
      "/guitars-photo/dangelico/solid/1/4.png",
      "/guitars-photo/dangelico/solid/1/5.png",
      "/guitars-photo/dangelico/solid/1/6.png",
    ],
    firm: "D'Angelico",
    type: "electric",
    video: "https://www.youtube.com/embed/k_nV8i9K0SM?si=KFvlqt2XM7RD9eI2",
    har: "Серія:	                 Standard\nМатеріал корпусу: Вільха\nОрієнтація:             Правостороння\nРозмір гітари:         Повнорозмірна\nГриф:                  	 Клен\nКріплення грифу:	 На болтах\nНакладка грифа:	 Клен\nПрофіль грифа:	 Стандартний 'С'\nТип звукознімачів: Роздільні сингли\nСхема звукознімачів:	S\nМензура:	          34' (864 мм)\nКількість ладів:	  20\nГарантія:	          12 місяців від виробника\nЕлектроніка:	          AlNiCo 5",
    pickup: "S-S",
    frets: "22",
    avail: "Є в наявнсті",
    code: "623345",
    audio: "/audio/electro1.mp3",
  },
  {
    id: 3,
    name: "DELUXE BRANDON NIEDERAUER ATLANTIC",
    cost: "73000",
    image: "/guitars-photo/dangelico/solid/2/main.png",
    images: [
      "/guitars-photo/dangelico/solid/2/1.png",
      "/guitars-photo/dangelico/solid/2/2.png",
      "/guitars-photo/dangelico/solid/2/3.png",
      "/guitars-photo/dangelico/solid/2/4.png",
      "/guitars-photo/dangelico/solid/2/5.png",
      "/guitars-photo/dangelico/solid/2/6.png",
    ],
    firm: "D'Angelico",
    type: "electric",
    video: "https://www.youtube.com/embed/Q4GvUBdmHTw?si=yiBc_TB31qjawjvc",
    har: "Серія:	                 Standard\nМатеріал корпусу: Вільха\nОрієнтація:             Правостороння\nРозмір гітари:         Повнорозмірна\nГриф:                  	 Клен\nКріплення грифу:	 На болтах\nНакладка грифа:	 Клен\nПрофіль грифа:	 Стандартний 'С'\nТип звукознімачів: Роздільні сингли\nСхема звукознімачів:	S\nМензура:	          34' (864 мм)\nКількість ладів:	  20\nГарантія:	          12 місяців від виробника\nЕлектроніка:	          AlNiCo 5",
    pickup: "S-S",
    frets: "22",
    avail: "Є в наявнсті",
    code: "126585",
    audio: "/audio/electro1.mp3",
  },
  {
    id: 4,
    name: "Player Precision Bass®",
    cost: "27000",
    image: "/guitars-photo/fender/bass/1/main.jpg",
    images: [
      "/guitars-photo/fender/bass/1/1.jpg",
      "/guitars-photo/fender/bass/1/2.jpg",
      "/guitars-photo/fender/bass/1/3.jpg",
      "/guitars-photo/fender/bass/1/4.jpg",
      "/guitars-photo/fender/bass/1/5.jpg",
      "/guitars-photo/fender/bass/1/6.jpg",
    ],
    firm: "Fender",
    type: "bass",
    video: "https://www.youtube.com/embed/55wAPrIoA6M?si=CzoJPMdesoq6p_dl",
    har: "Серія:	                 Standard\nМатеріал корпусу: Вільха\nОрієнтація:             Правостороння\nРозмір гітари:         Повнорозмірна\nГриф:                  	 Клен\nКріплення грифу:	 На болтах\nНакладка грифа:	 Клен\nПрофіль грифа:	 Стандартний 'С'\nТип звукознімачів: Роздільні сингли\nСхема звукознімачів:	S\nМензура:	          34' (864 мм)\nКількість ладів:	  20\nГарантія:	          12 місяців від виробника\nЕлектроніка:	          AlNiCo 5",
    pickup: "S",
    frets: "20",
    avail: "Є в наявнсті",
    code: "947363",
    audio: "/audio/bass2.mp3",
  },
  {
    id: 5,
    name: "FA-125CE Dreadnought",
    cost: "7999",
    image: "/guitars-photo/fender/acoustic/1/main.jpg",
    images: [
      "/guitars-photo/fender/acoustic/1/1.jpg",
      "/guitars-photo/fender/acoustic/1/2.jpg",
      "/guitars-photo/fender/acoustic/1/3.jpg",
      "/guitars-photo/fender/acoustic/1/4.jpg",
      "/guitars-photo/fender/acoustic/1/5.jpg",
      "/guitars-photo/fender/acoustic/1/6.jpg",
    ],
    firm: "Fender",
    type: "acoustic",
    video: "https://www.youtube.com/embed/yJ4-3hO7Rbc?si=ONZvbBm_DlgWry4h",
    har: "Серія:	                 Standard\nМатеріал корпусу: Вільха\nОрієнтація:             Правостороння\nРозмір гітари:         Повнорозмірна\nГриф:                  	 Горіх\nКріплення грифу:	 На болтах\nНакладка грифа:	 Липа\nПрофіль грифа:	 Стандартний 'С'\nТип звукознімачів: Немає\nСхема звукознімачів:	Немає\nМензура:	          25.3' (643 мм)\nКількість ладів:	  20\nГарантія:	          12 місяців від виробника\n",
    pickup: "",
    frets: "20",
    avail: "Є в наявнсті",
    code: "856396",
    audio: "/audio/ac2.mp3",
  },
  {
    id: 6,
    name: "GIBSON LES PAUL MELODY MAKER 2014 MMS",
    cost: "17475",
    image: "/guitars-photo/gibson/electric/1/main.jpg",
    images: [
      "/guitars-photo/gibson/electric/1/1.webp",
      "/guitars-photo/gibson/electric/1/2.webp",
      "/guitars-photo/gibson/electric/1/3.webp",
      "/guitars-photo/gibson/electric/1/4.webp",
      "/guitars-photo/gibson/electric/1/5.webp",
    ],
    firm: "Gibson",
    type: "electric",
    video: "https://www.youtube.com/embed/yJ4-3hO7Rbc?si=ONZvbBm_DlgWry4h",
    har: "Серія:	                 Standard\nМатеріал корпусу: Вільха\nОрієнтація:             Правостороння\nРозмір гітари:         Повнорозмірна\nГриф:                  	 Горіх\nКріплення грифу:	 На болтах\nНакладка грифа:	 Липа\nПрофіль грифа:	 Стандартний 'С'\nТип звукознімачів: Немає\nСхема звукознімачів:	Немає\nМензура:	          25.3' (643 мм)\nКількість ладів:	  20\nГарантія:	          12 місяців від виробника\n",
    pickup: "S-S",
    frets: "22",
    avail: "Немає в наявнсті",
    code: "554673",
    audio: "/audio/electro1.mp3",
  },
  {
    id: 7,
    name: "JACKSON JS11 DINKY WHITE",
    cost: "6450",
    image: "/guitars-photo/jackson/electric/1/main.jpg",
    images: [
      "/guitars-photo/jackson/electric/1/1.webp",
      "/guitars-photo/jackson/electric/1/2.webp",
      "/guitars-photo/jackson/electric/1/3.webp",
      "/guitars-photo/jackson/electric/1/4.webp",
      "/guitars-photo/jackson/electric/1/5.webp",
    ],
    firm: "Jackson",
    type: "electric",
    video: "https://www.youtube.com/embed/yJ4-3hO7Rbc?si=ONZvbBm_DlgWry4h",
    har: "Серія:	                 JS\nМатеріал корпусу: Липа\nОрієнтація:             Правостороння\nРозмір гітари:         Повнорозмірна\nГриф:                  	 Клен\nКріплення грифу:	 болчене\nНакладка грифа:	 Липа\nПрофіль грифа:	 Стандартний 'С'\nТип звукознімачів: Hight Output Humbucking\nСхема звукознімачів:	H-H\nМензура:	          25.5' (648 мм)\nКількість ладів:	  22\nГарантія:	          12 місяців від виробника\n",
    pickup: "H-H",
    frets: "22",
    avail: "Є в наявнсті",
    code: "252482",
    audio: "/audio/electro1.mp3",
  },
  {
    id: 8,
    name: "DANGELICO PREMIER GRAMERCY LS",
    cost: "13700",
    image: "/guitars-photo/dangelico/acoust/1/main.webp",
    images: [
      "/guitars-photo/dangelico/acoust/1/1.jpg",
      "/guitars-photo/dangelico/acoust/1/2.jpg",
      "/guitars-photo/dangelico/acoust/1/3.webp",
      "/guitars-photo/dangelico/acoust/1/4.webp",
      "/guitars-photo/dangelico/acoust/1/5.webp",
      "/guitars-photo/dangelico/acoust/1/6.webp",
    ],
    firm: "D'Angelico",
    type: "acoustic",
    video: "https://www.youtube.com/embed/yJ4-3hO7Rbc?si=ONZvbBm_DlgWry4h",
    har: "Серія:	                 LS\nМатеріал корпусу: Липа\nОрієнтація:             Правостороння\nРозмір гітари:         Повнорозмірна\nГриф:                  	 Мербау\nКріплення грифу:	 болчене\nНакладка грифа:	 Липа\nПрофіль грифа:	 Стандартний 'С'\nТип звукознімачів: -\nСхема звукознімачів:	-\nМензура:	          25.5' (648 мм)\nКількість ладів:	  20\nГарантія:	          12 місяців від виробника\n",
    pickup: "",
    frets: "20",
    avail: "Є в наявнсті",
    code: "484950",
    audio: "/audio/ac1.mp3",
  },
  {
    id: 9,
    name: "JACKSON X SERIES BASS CBXNTL GLOSS",
    cost: "30000",
    image: "/guitars-photo/jackson/bass/1/main.jpg",
    images: [
      "/guitars-photo/jackson/bass/1/1.jpg",
      "/guitars-photo/jackson/bass/1/2.jpg",
      "/guitars-photo/jackson/bass/1/3.jpg",
      "/guitars-photo/jackson/bass/1/4.jpg",
      "/guitars-photo/jackson/bass/1/5.jpg",
      "/guitars-photo/jackson/bass/1/6.jpg",
      "/guitars-photo/jackson/bass/1/7.jpg",
    ],
    firm: "Jackson",
    type: "bass",
    video: "https://www.youtube.com/embed/yJ4-3hO7Rbc?si=ONZvbBm_DlgWry4h",
    har: "Серія:	                 X\nМатеріал корпусу: Липа\nОрієнтація:             Правостороння\nРозмір гітари:         Повнорозмірна\nГриф:                  	 Клен\nКріплення грифу:	 На болтах\nНакладка грифа:	 Липа\nПрофіль грифа:	 Стандартний 'С'\nТип звукознімачів: Hight Output Humbucking\nСхема звукознімачів:	S-S\nМензура:	          34'\nКількість ладів:	  19\nГарантія:	          12 місяців від виробника\n",
    pickup: "H-H",
    frets: "19",
    avail: "Є в наявнсті",
    code: "252482",
    audio: "/audio/bass1.mp3",
  },
  {
    id: 10,
    name: "SQUIER CLASSIC VIBE '70S PRECISION BASS MAPLE",
    cost: "22000",
    image: "/guitars-photo/fender/bass/2/main.jpg",
    images: [
      "/guitars-photo/fender/bass/2/1.jpg",
      "/guitars-photo/fender/bass/2/2.jpg",
      "/guitars-photo/fender/bass/2/3.jpg",
      "/guitars-photo/fender/bass/2/4.jpg",
      "/guitars-photo/fender/bass/2/5.jpg",
    ],
    firm: "Fender",
    type: "bass",
    video: "https://www.youtube.com/embed/yJ4-3hO7Rbc?si=ONZvbBm_DlgWry4h",
    har: "Серія:	                 Squier\nМатеріал корпусу: Липа\nОрієнтація:             Правостороння\nРозмір гітари:         Повнорозмірна\nГриф:                  	 Клен\nКріплення грифу:	 болчене\nНакладка грифа:	 Липа\nПрофіль грифа:	 Стандартний 'С'\nТип звукознімачів: Hight Output Single\nСхема звукознімачів:	S-S\nМензура:	          25.5' (648 мм)\nКількість ладів:	  22\nГарантія:	          12 місяців від виробника\n",
    pickup: "S-S",
    frets: "20",
    avail: "Немає в наявнсті",
    code: "102452",
    audio: "/audio/bass1.mp3",
  },
  {
    id: 11,
    name: "GIBSON 2018 FLYING V AGED",
    cost: "45017",
    image: "/guitars-photo/gibson/electric/2/main.jpg",
    images: [
      "/guitars-photo/gibson/electric/2/1.webp",
      "/guitars-photo/gibson/electric/2/2.webp",
      "/guitars-photo/gibson/electric/2/3.webp",
      "/guitars-photo/gibson/electric/2/4.webp",
      "/guitars-photo/gibson/electric/2/5.webp",
      "/guitars-photo/gibson/electric/2/6.webp",
    ],
    firm: "Gibson",
    type: "electric",
    video: "https://www.youtube.com/embed/DPrLpVYEkVM?si=kDPfTCzdK-NJk0u2",
    har: "Серія:	                 FLYING V\nМатеріал корпусу: Липа\nОрієнтація:             Правостороння\nРозмір гітари:         Повнорозмірна\nГриф:                  	 Махогон\nКріплення грифу:	 вклеїний\nНакладка грифа:	 Липа\nПрофіль грифа:	 Стандартний 'С'\nТип звукознімачів: Hight Output Humbucking\nСхема звукознімачів:	H-H\nМензура:	          24.75' (648 мм)\nКількість ладів:	  22\nГарантія:	          12 місяців від виробника\n",
    pickup: "H-H",
    frets: "22",
    avail: "Є в наявнсті",
    code: "64678",
    audio: "/audio/electro1.mp3",
  },
];
